/** Postgres tables in `supabase/schema.sql` replace these Firestore collection ids. */
export const COLLECTIONS = {
  users: 'users',
  fuelTypes: 'fuelTypes',
  nozzles: 'nozzles',
  shifts: 'shifts',
  shiftReadings: 'shiftReadings',
  shiftReconciliations: 'shiftReconciliations',
  creditCustomers: 'creditCustomers',
  creditSales: 'creditSales',
  creditPayments: 'creditPayments',
  ledgerEntries: 'ledgerEntries',
  fuelTankDips: 'fuelTankDips',
  fuelReceipts: 'fuelReceipts',
  fuelDipLedger: 'fuelDipLedger',
  lubricants: 'lubricants',
  lubricantStockEntries: 'lubricantStockEntries',
  lubricantSales: 'lubricantSales',
  stationSettings: 'stationSettings',
} as const;
